# Generated by Django 3.1.1 on 2020-09-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shorten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(verbose_name='Enter original uri ')),
                ('shorturi', models.URLField(editable=False, unique=True, verbose_name='save the model for shorten uri')),
            ],
        ),
    ]
