# Generated by Django 3.1.1 on 2020-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorten',
            name='shorturi',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='save the model for shorten uri'),
        ),
    ]
