# Generated by Django 3.1.1 on 2020-09-05 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20200904_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(verbose_name='Enter original uri ')),
                ('shorturi', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='save the model for shorten uri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
