# Generated by Django 3.1.1 on 2020-09-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200907_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershort',
            name='shorturi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='save the model for shorten uri'),
        ),
    ]
